-- ============================================================================
-- RestaurantOS V1 database schema (PostgreSQL 16+)
-- Phase 2 artifact (WP-2.1). Sources: Toast report ER model + state machines,
-- Square report payment decomposition, founder KDS/close-day requirements.
-- Status: DRAFT for review. Becomes migration 0001 when the app tree exists.
--
-- Conventions (Decision D14):
--   * Every id is UUID, generated by the CLIENT (ULID-in-UUID form), never by
--     the database. A terminal must be able to create a check offline.
--   * All money is BIGINT minor units (cents). No floats, no numerics, ever.
--   * Enums are TEXT + CHECK constraints, not Postgres enums: adding a state
--     is an expand/contract migration, not a type rebuild.
--   * org_id and location_id ride on every operational table from day one
--     (multi-location readiness, per master plan) even though V1 is
--     single-location.
--   * "checks" not "check" (reserved word), "guest" language elsewhere.
--   * Timestamps are timestamptz, always UTC; business calendar lives in
--     business_day, not in timestamp arithmetic.
--   * The DATABASE enforces shape, uniqueness, and referential integrity.
--     The DOMAIN LAYER enforces transitions and money conservation.
--     See domain-model.md for the split.
-- ============================================================================

-- ============================================================================
-- 1. TENANCY, PEOPLE, DEVICES
-- ============================================================================

CREATE TABLE organization (
  id            UUID PRIMARY KEY,
  name          TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE location (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  name          TEXT NOT NULL,
  timezone      TEXT NOT NULL,                 -- e.g. 'America/New_York'
  currency      CHAR(3) NOT NULL DEFAULT 'USD',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE device (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  location_id   UUID NOT NULL REFERENCES location(id),
  name          TEXT NOT NULL,                 -- 'Terminal 1', 'Expo KDS'
  kind          TEXT NOT NULL CHECK (kind IN ('terminal','handheld','kds','edge')),
  enrolled_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at  TIMESTAMPTZ,
  revoked_at    TIMESTAMPTZ                    -- soft revoke; devices are never deleted
);

CREATE TABLE employee (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  location_id   UUID NOT NULL REFERENCES location(id),
  display_name  TEXT NOT NULL,                 -- what the check header shows
  pin_hash      TEXT NOT NULL,                 -- argon2id; NEVER the pin itself
  active        BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE role (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  name          TEXT NOT NULL                  -- 'Server', 'Manager', 'Line cook'
);

-- Permission keys are a closed set owned by the domain layer, seeded by
-- migration. Examples: 'check.void_item', 'check.discount', 'check.reopen',
-- 'drawer.open', 'drawer.close', 'day.close', 'menu.publish'.
CREATE TABLE permission (
  key           TEXT PRIMARY KEY,
  description   TEXT NOT NULL
);

CREATE TABLE role_permission (
  role_id        UUID NOT NULL REFERENCES role(id),
  permission_key TEXT NOT NULL REFERENCES permission(key),
  PRIMARY KEY (role_id, permission_key)
);

CREATE TABLE employee_role (
  employee_id   UUID NOT NULL REFERENCES employee(id),
  role_id       UUID NOT NULL REFERENCES role(id),
  PRIMARY KEY (employee_id, role_id)
);

-- ============================================================================
-- 2. THE BUSINESS CALENDAR
-- Three separate concepts, per the close-day design discussion:
--   business_day  = the accounting boundary (one per location per date)
--   shift         = an employee working (many per day)
--   drawer_session= a physical till from open count to close count
-- A 1 AM Saturday check belongs to Friday's business_day. That mapping is a
-- domain rule at check-open time, not timestamp arithmetic at report time.
-- ============================================================================

CREATE TABLE business_day (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  location_id   UUID NOT NULL REFERENCES location(id),
  service_date  DATE NOT NULL,
  status        TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
  opened_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at     TIMESTAMPTZ,
  closed_by     UUID REFERENCES employee(id),
  UNIQUE (location_id, service_date)
);

CREATE TABLE shift (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  location_id   UUID NOT NULL REFERENCES location(id),
  business_day_id UUID NOT NULL REFERENCES business_day(id),
  employee_id   UUID NOT NULL REFERENCES employee(id),
  clock_in      TIMESTAMPTZ NOT NULL,
  clock_out     TIMESTAMPTZ,
  declared_tips_minor BIGINT CHECK (declared_tips_minor >= 0)
);

-- ============================================================================
-- 3. THE ROOM
-- Floor plan is data (proven in the prototype): position and shape live on
-- the table row, drawn once by the operator during setup.
-- ============================================================================

CREATE TABLE dining_area (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  location_id   UUID NOT NULL REFERENCES location(id),
  name          TEXT NOT NULL,                 -- 'Sala', 'Terrazza', 'Bar'
  sort          INT NOT NULL DEFAULT 0
);

CREATE TABLE dining_table (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  area_id       UUID NOT NULL REFERENCES dining_area(id),
  name          TEXT NOT NULL,
  seats         INT NOT NULL CHECK (seats > 0),
  shape         TEXT NOT NULL DEFAULT 'rect' CHECK (shape IN ('rect','round','stool','booth')),
  pos           JSONB NOT NULL DEFAULT '{}'    -- {x,y,w,h} as % of the room
);

-- A party is one seating of one group: it can outlive a table transfer and
-- can hold multiple checks (split parties). Table status on the floor plan
-- is DERIVED from parties/checks/tickets, never stored on dining_table.
CREATE TABLE party (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  location_id   UUID NOT NULL REFERENCES location(id),
  table_id      UUID REFERENCES dining_table(id),   -- NULL = takeout/tab
  covers        INT NOT NULL CHECK (covers > 0),
  seated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  cleared_at    TIMESTAMPTZ
);

-- ============================================================================
-- 4. MENU CONFIGURATION (live, editable)
-- The modifier model is a graph: groups are reusable across items, options
-- carry min/max, and a modifier can open a nested child group. A flat
-- modifiers[] array cannot represent a real menu. [Toast report]
-- ============================================================================

CREATE TABLE prep_station (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  location_id   UUID NOT NULL REFERENCES location(id),
  name          TEXT NOT NULL                  -- 'FORNO', 'SAUTE', 'GRILL', 'FREDDO', 'BAR'
);

CREATE TABLE menu (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  location_id   UUID NOT NULL REFERENCES location(id),
  name          TEXT NOT NULL,                 -- 'Dinner', 'Lunch', 'Bar'
  active        BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE menu_group (
  id            UUID PRIMARY KEY,
  menu_id       UUID NOT NULL REFERENCES menu(id),
  name          TEXT NOT NULL,                 -- 'Antipasti', 'Primi'
  sort          INT NOT NULL DEFAULT 0
);

CREATE TABLE menu_item (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  name          TEXT NOT NULL,
  description   TEXT,
  course        TEXT NOT NULL DEFAULT 'MAIN',  -- location-configurable course keys
  station_id    UUID REFERENCES prep_station(id),
  tax_class     TEXT NOT NULL DEFAULT 'standard'
);

-- Many-to-many: an item can appear on several menus/groups, and the path can
-- matter (lunch price vs dinner price via variation overrides later).
CREATE TABLE menu_group_item (
  group_id      UUID NOT NULL REFERENCES menu_group(id),
  item_id       UUID NOT NULL REFERENCES menu_item(id),
  sort          INT NOT NULL DEFAULT 0,
  PRIMARY KEY (group_id, item_id)
);

CREATE TABLE item_variation (
  id            UUID PRIMARY KEY,
  item_id       UUID NOT NULL REFERENCES menu_item(id),
  name          TEXT NOT NULL,                 -- 'Glass', 'Bottle'; default = item name
  price_minor   BIGINT NOT NULL CHECK (price_minor >= 0),
  is_default    BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE modifier_group (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  name          TEXT NOT NULL,                 -- 'Pasta', 'Temperature', 'Additions'
  min_select    INT NOT NULL DEFAULT 0 CHECK (min_select >= 0),
  max_select    INT CHECK (max_select IS NULL OR max_select >= min_select)
);

CREATE TABLE modifier (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  name          TEXT NOT NULL,                 -- 'Tagliatelle', 'Add shrimp'
  price_minor   BIGINT NOT NULL DEFAULT 0 CHECK (price_minor >= 0)
);

CREATE TABLE modifier_group_option (
  group_id      UUID NOT NULL REFERENCES modifier_group(id),
  modifier_id   UUID NOT NULL REFERENCES modifier(id),
  sort          INT NOT NULL DEFAULT 0,
  is_default    BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (group_id, modifier_id)
);

-- Assignment of reusable groups to items.
CREATE TABLE item_modifier_group (
  item_id       UUID NOT NULL REFERENCES menu_item(id),
  group_id      UUID NOT NULL REFERENCES modifier_group(id),
  sort          INT NOT NULL DEFAULT 0,
  PRIMARY KEY (item_id, group_id)
);

-- Nesting: choosing a modifier can open a child group ('Add shrimp' opens
-- 'Cooked how?'). Depth is limited by the DOMAIN layer (V1: depth 2), the
-- schema permits recursion so a deeper menu never needs a migration.
CREATE TABLE modifier_child_group (
  modifier_id     UUID NOT NULL REFERENCES modifier(id),
  child_group_id  UUID NOT NULL REFERENCES modifier_group(id),
  PRIMARY KEY (modifier_id, child_group_id)
);

-- Live availability / 86 board. remaining NULL = not counted (always
-- available unless is_86). This table is hot and tiny by design.
CREATE TABLE item_availability (
  location_id   UUID NOT NULL REFERENCES location(id),
  item_id       UUID NOT NULL REFERENCES menu_item(id),
  remaining     INT CHECK (remaining IS NULL OR remaining >= 0),
  is_86         BOOLEAN NOT NULL DEFAULT false,
  updated_by    UUID REFERENCES employee(id),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (location_id, item_id)
);

-- ============================================================================
-- 5. MENU SNAPSHOTS (immutable, published)
-- Editing tomorrow's menu must never rewrite yesterday's check. Publishing
-- freezes the whole resolved menu graph into one immutable document that
-- devices cache for offline boot and that order lines reference forever.
-- The live tables above are the EDITOR; snapshots are what SERVICE runs on.
-- ============================================================================

CREATE TABLE menu_snapshot (
  id            UUID PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organization(id),
  location_id   UUID NOT NULL REFERENCES location(id),
  version       INT  NOT NULL,
  document      JSONB NOT NULL,                -- fully resolved menu graph
  published_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_by  UUID NOT NULL REFERENCES employee(id),
  UNIQUE (location_id, version)
);
-- No UPDATE or DELETE is ever issued against menu_snapshot. Enforced by a
-- revoke in the role grants and by the domain layer; a trigger guard is
-- added in the hardening pass.

-- ============================================================================
-- 6. CHECKS AND ORDER LINES
-- order ≠ check: the check is the financial container that tenders settle;
-- kitchen fulfillment state NEVER appears on these tables. [Toast report]
-- ============================================================================

CREATE TABLE checks (
  id              UUID PRIMARY KEY,
  org_id          UUID NOT NULL REFERENCES organization(id),
  location_id     UUID NOT NULL REFERENCES location(id),
  business_day_id UUID NOT NULL REFERENCES business_day(id),
  party_id        UUID NOT NULL REFERENCES party(id),
  check_no        BIGINT NOT NULL,             -- human-facing, per location
  server_id       UUID NOT NULL REFERENCES employee(id),
  menu_snapshot_id UUID NOT NULL REFERENCES menu_snapshot(id),
  status          TEXT NOT NULL DEFAULT 'open' CHECK (status IN
                    ('open','partially_paid','paid','closed','reopened','voided')),
  covers          INT NOT NULL CHECK (covers > 0),
  version         BIGINT NOT NULL DEFAULT 0,   -- optimistic concurrency; bumped by every command
  opened_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at       TIMESTAMPTZ,
  UNIQUE (location_id, check_no)
);

CREATE INDEX idx_checks_open ON checks (location_id, business_day_id) WHERE status <> 'closed' AND status <> 'voided';

CREATE TABLE order_item (
  id              UUID PRIMARY KEY,
  check_id        UUID NOT NULL REFERENCES checks(id),
  menu_snapshot_id UUID NOT NULL REFERENCES menu_snapshot(id),
  item_id         UUID NOT NULL,               -- id within the snapshot document
  variation_id    UUID,
  captured_name   TEXT NOT NULL,               -- denormalized on purpose:
  unit_price_minor BIGINT NOT NULL CHECK (unit_price_minor >= 0),  -- the line is
  tax_class       TEXT NOT NULL,               -- self-describing forever, even if
  course          TEXT NOT NULL,               -- the snapshot format evolves
  station_key     TEXT,
  quantity        INT NOT NULL CHECK (quantity > 0),
  seat_no         INT NOT NULL DEFAULT 1 CHECK (seat_no > 0),
  note            TEXT,
  status          TEXT NOT NULL DEFAULT 'unsent' CHECK (status IN ('unsent','sent','voided')),
  void_reason     TEXT,
  voided_by       UUID REFERENCES employee(id),
  void_approved_by UUID REFERENCES employee(id),
  created_by      UUID NOT NULL REFERENCES employee(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- a void must carry its paperwork:
  CONSTRAINT void_has_reason CHECK (status <> 'voided' OR (void_reason IS NOT NULL AND void_approved_by IS NOT NULL))
);

CREATE INDEX idx_order_item_check ON order_item (check_id);

CREATE TABLE order_item_modifier (
  id              UUID PRIMARY KEY,
  order_item_id   UUID NOT NULL REFERENCES order_item(id),
  modifier_id     UUID,                        -- id within the snapshot
  captured_name   TEXT NOT NULL,
  price_minor     BIGINT NOT NULL DEFAULT 0 CHECK (price_minor >= 0),
  quantity        INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
  is_allergy_flag BOOLEAN NOT NULL DEFAULT false
);

-- Discounts, comps, service charges, auto-gratuity: all adjustments, all
-- audited, all requiring an actor. Auto-gratuity policy (party size
-- threshold) is location config applied by the domain layer; the schema
-- just records what was applied. [Matt question, deck A]
CREATE TABLE check_adjustment (
  id              UUID PRIMARY KEY,
  check_id        UUID NOT NULL REFERENCES checks(id),
  kind            TEXT NOT NULL CHECK (kind IN ('discount','comp','service_charge','auto_gratuity')),
  captured_name   TEXT NOT NULL,               -- 'Industry 10%'
  amount_minor    BIGINT,                      -- exactly one of amount / percent
  percent_bp      INT,                         -- basis points: 10% = 1000
  reason          TEXT,
  applied_by      UUID NOT NULL REFERENCES employee(id),
  approved_by     UUID REFERENCES employee(id),
  applied_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT amount_xor_percent CHECK ((amount_minor IS NULL) <> (percent_bp IS NULL))
);

-- ============================================================================
-- 7. KITCHEN: DISPATCHES AND TICKETS
-- A dispatch is the immutable answer to "what did we tell the kitchen, and
-- when". Tickets are the kitchen's working projection of a dispatch, split
-- by station. Per-item completion (the sous chef requirement) lives on
-- kitchen_ticket_item.
-- ============================================================================

CREATE TABLE order_dispatch (
  id              UUID PRIMARY KEY,
  check_id        UUID NOT NULL REFERENCES checks(id),
  course          TEXT NOT NULL,
  fired_by        UUID NOT NULL REFERENCES employee(id),
  device_id       UUID NOT NULL REFERENCES device(id),
  fired_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Immutable: no UPDATE ever. A fired course that must change is a VOID on
-- the order_item plus, where needed, a new dispatch.

CREATE TABLE dispatch_item (
  dispatch_id     UUID NOT NULL REFERENCES order_dispatch(id),
  order_item_id   UUID NOT NULL REFERENCES order_item(id),
  PRIMARY KEY (dispatch_id, order_item_id),
  -- one item can only ever be dispatched once:
  UNIQUE (order_item_id)
);

CREATE TABLE kitchen_ticket (
  id              UUID PRIMARY KEY,
  dispatch_id     UUID NOT NULL REFERENCES order_dispatch(id),
  station_id      UUID REFERENCES prep_station(id),  -- NULL = expo/all
  status          TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','served','recalled')),
  served_at       TIMESTAMPTZ,
  served_by       UUID REFERENCES employee(id)
);

CREATE TABLE kitchen_ticket_item (
  ticket_id       UUID NOT NULL REFERENCES kitchen_ticket(id),
  order_item_id   UUID NOT NULL REFERENCES order_item(id),
  done            BOOLEAN NOT NULL DEFAULT false,   -- per-item bump; toggling is allowed
  done_at         TIMESTAMPTZ,
  PRIMARY KEY (ticket_id, order_item_id)
);

-- ============================================================================
-- 8. PAYMENTS
-- payment_intent -> payment_attempt(s) -> payment -> refund(s).
-- Never one boolean; retries are rows, not overwrites. [Square + Toast]
-- NEVER stored anywhere in this database: PAN, track data, CVV, cardholder
-- name from the card. Only provider tokens and references.
-- ============================================================================

CREATE TABLE payment_intent (
  id              UUID PRIMARY KEY,
  check_id        UUID NOT NULL REFERENCES checks(id),
  split_label     TEXT,                        -- 'Seat 2', 'Guest 3', 'Whole check'
  amount_minor    BIGINT NOT NULL CHECK (amount_minor > 0),
  tip_minor       BIGINT NOT NULL DEFAULT 0 CHECK (tip_minor >= 0),
  status          TEXT NOT NULL DEFAULT 'created' CHECK (status IN
                    ('created','processing','succeeded','canceled','failed')),
  created_by      UUID NOT NULL REFERENCES employee(id),
  device_id       UUID NOT NULL REFERENCES device(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payment_attempt (
  id              UUID PRIMARY KEY,
  intent_id       UUID NOT NULL REFERENCES payment_intent(id),
  method          TEXT NOT NULL CHECK (method IN ('card_present','cash','gift','other')),
  provider        TEXT,                        -- 'stripe' | 'adyen' | NULL for cash
  provider_ref    TEXT,                        -- provider's id; the ONLY card linkage
  status          TEXT NOT NULL CHECK (status IN
                    ('initiated','reader_waiting','offline_pending',
                     'authorized','captured','declined','failed','voided')),
  amount_minor    BIGINT NOT NULL CHECK (amount_minor > 0),
  failure_code    TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at     TIMESTAMPTZ
);

CREATE INDEX idx_attempt_pending ON payment_attempt (status) WHERE status IN ('offline_pending','reader_waiting','initiated');

-- A payment exists only once value has actually been accepted (cash taken,
-- card authorized, or card accepted offline pending upload). The UI rule
-- "pending upload is never displayed as paid" reads payment.status.
CREATE TABLE payment (
  id              UUID PRIMARY KEY,
  intent_id       UUID NOT NULL REFERENCES payment_intent(id),
  attempt_id      UUID NOT NULL REFERENCES payment_attempt(id),
  method          TEXT NOT NULL CHECK (method IN ('card','cash','gift','other')),
  amount_minor    BIGINT NOT NULL CHECK (amount_minor > 0),
  tip_minor       BIGINT NOT NULL DEFAULT 0 CHECK (tip_minor >= 0),
  status          TEXT NOT NULL CHECK (status IN
                    ('accepted_offline','authorized','captured','settled','refunded_partial','refunded')),
  taken_by        UUID NOT NULL REFERENCES employee(id),
  taken_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE refund (
  id              UUID PRIMARY KEY,
  payment_id      UUID NOT NULL REFERENCES payment(id),
  amount_minor    BIGINT NOT NULL CHECK (amount_minor > 0),
  reason          TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'requested' CHECK (status IN
                    ('requested','processing','succeeded','failed')),
  provider_ref    TEXT,
  requested_by    UUID NOT NULL REFERENCES employee(id),
  approved_by     UUID REFERENCES employee(id),
  requested_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at     TIMESTAMPTZ
);

-- ============================================================================
-- 9. CASH
-- Cash has no processor webhooks; the ledger of immutable cash_event rows is
-- the only truth. Expected drawer = opening float + sum(events). Over/short
-- is computed at close, recorded, and never edited.
-- ============================================================================

CREATE TABLE cash_drawer (
  id              UUID PRIMARY KEY,
  org_id          UUID NOT NULL REFERENCES organization(id),
  location_id     UUID NOT NULL REFERENCES location(id),
  name            TEXT NOT NULL                -- 'Front drawer', 'Bar drawer'
);

CREATE TABLE drawer_session (
  id              UUID PRIMARY KEY,
  drawer_id       UUID NOT NULL REFERENCES cash_drawer(id),
  business_day_id UUID NOT NULL REFERENCES business_day(id),
  opened_by       UUID NOT NULL REFERENCES employee(id),
  opened_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  opening_float_minor BIGINT NOT NULL CHECK (opening_float_minor >= 0),
  closed_by       UUID REFERENCES employee(id),
  closed_at       TIMESTAMPTZ,
  counted_minor   BIGINT CHECK (counted_minor >= 0),   -- the physical count
  expected_minor  BIGINT,                              -- computed + frozen at close
  over_short_minor BIGINT                              -- counted - expected, frozen
);

-- Only one open session per physical drawer:
CREATE UNIQUE INDEX idx_drawer_one_open ON drawer_session (drawer_id) WHERE closed_at IS NULL;

CREATE TABLE cash_event (
  id              UUID PRIMARY KEY,
  drawer_session_id UUID NOT NULL REFERENCES drawer_session(id),
  kind            TEXT NOT NULL CHECK (kind IN ('sale','refund','pay_in','pay_out','drop','count')),
  amount_minor    BIGINT NOT NULL,             -- signed: pay_out/drop are negative
  payment_id      UUID REFERENCES payment(id), -- set for kind='sale'/'refund'
  reason          TEXT,
  employee_id     UUID NOT NULL REFERENCES employee(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Append-only: no UPDATE, no DELETE. A mistaken event is corrected by a
-- compensating event, so the ledger reads like what actually happened.

-- ============================================================================
-- 10. SYNC, AUDIT, OUTBOX
-- The operation journal is the heart of local-first: a device uploads
-- commands with client-generated operation ids; replaying the same id
-- returns the recorded result instead of executing twice. [Toast report]
-- ============================================================================

CREATE TABLE sync_operation (
  operation_id    UUID PRIMARY KEY,            -- client-generated; THE idempotency key
  org_id          UUID NOT NULL REFERENCES organization(id),
  location_id     UUID NOT NULL REFERENCES location(id),
  device_id       UUID NOT NULL REFERENCES device(id),
  employee_id     UUID REFERENCES employee(id),
  aggregate_type  TEXT NOT NULL,               -- 'check', 'drawer_session', ...
  aggregate_id    UUID NOT NULL,
  expected_version BIGINT,
  command         JSONB NOT NULL,              -- the full command envelope
  status          TEXT NOT NULL CHECK (status IN ('applied','conflict','rejected')),
  result          JSONB,                       -- what the client gets on replay
  client_ts       TIMESTAMPTZ NOT NULL,
  applied_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sync_aggregate ON sync_operation (aggregate_type, aggregate_id);

-- Append-only audit of privileged and financial actions. Every void, comp,
-- discount, reopen, transfer, drawer event, day close, and menu publish
-- lands here with actor, device, and approver.
CREATE TABLE audit_event (
  id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  org_id          UUID NOT NULL,
  location_id     UUID NOT NULL,
  at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  actor_id        UUID,                        -- employee; NULL = system
  device_id       UUID,
  approved_by     UUID,                        -- second employee for approvals
  action          TEXT NOT NULL,               -- 'check.item_voided', 'day.closed'
  aggregate_type  TEXT NOT NULL,
  aggregate_id    UUID NOT NULL,
  detail          JSONB NOT NULL DEFAULT '{}'
);

CREATE INDEX idx_audit_aggregate ON audit_event (aggregate_type, aggregate_id);

-- Transactional outbox (Decision D3): externally visible events are written
-- in the same transaction as the state change, and a relay publishes them.
CREATE TABLE outbox (
  id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  topic           TEXT NOT NULL,               -- 'order.dispatched', 'payment.captured'
  payload         JSONB NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at    TIMESTAMPTZ
);

CREATE INDEX idx_outbox_unpublished ON outbox (id) WHERE published_at IS NULL;

-- ============================================================================
-- END OF SCHEMA
-- 44 tables. Verified against PostgreSQL 17: applies clean with
-- ON_ERROR_STOP, full org->check->payment FK chain inserts, and constraint
-- tests (void_has_reason, amount_xor_percent, one-open-drawer-session,
-- non-negative money, one-business-day-per-date) all behave as designed,
-- including the lunch/dinner drawer swap (close session, reopen same day).
-- What the schema deliberately does NOT contain:
--   * No 'paid' boolean anywhere.
--   * No kitchen state on checks or order lines.
--   * No card data of any kind.
--   * No stored table status (derived), no stored check totals (computed by
--     the money engine; totals shown to guests are reproducible from lines,
--     adjustments, and the tax engine, and asserted equal in tests).
--   * No lunch/dinner special-casing: many shifts + many drawer sessions
--     roll up into one business_day, so split service works by construction.
-- ============================================================================
